### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by tsh-gitusr-1** [Sumudu-Sahan/LinkedInManager#1]
I have used the library and is working great for me, I just wanted to know if there is a way to log out using your implementation, if not then can you point me in the right direction.

**Comment by surbhiv25** [comment]
@Sumudu-Sahan Any update for the same ?

**Comment by Sumudu-Sahan** [comment]
Hi all,

Please check with the latest version (V1.01.00)

What's new on V1.01.00
* Logout option added (Please refer the readme file)
* Can check if the user is logged in or not
* Can check user's logged mode
