### ISSUE TITLE
How to get linkedin public profile link using this lib?

### ISSUE THREAD

**Issue by NagarjunaReddyP** [Sumudu-Sahan/LinkedInManager#2]
i'm implemented this library working fine facing some issues.

1) If user cancel or not accept permission tried to implemented "linkedInRequestManager.dismissAuthenticateView();" but it's not working.

2) How to get public profile of login user.

**Comment by Sumudu-Sahan** [comment]
Hi,

Please check with the V1.01.00 release
1. You can parse a boolean value when initializing the SDK (to enable, disable popup dismiss function)
2. You can get only the lite profile details and the email address of the user
